version: 2.1

# Orb definition
orbs:
  aws-ecr: circleci/aws-ecr@0.0.4


# Executors definition
executors:
  py_executor:
    parameters:
      PY_VERSION:
        type: string
        default: 3.7.1
    docker:
      - image: circleci/python:<< parameters.PY_VERSION >>
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb


commands:
  docker_build:
    description: "build the Docker image for DFly Web Application"
    steps:
      - run: docker build -t fdfly-webapp:latest .
          

jobs:
  build_deploy:
    executor: py_executor
    steps:
      - checkout
      - setup_remote_docker
      - docker_build
      - aws-ecr/build_and_push_image:
          region: "${AWS_DEFAULT_REGION}"
          aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
          aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          create-repo: true
          repo: "${CIRCLE_PROJECT_REPONAME}"
          tag: "${CIRCLE_SHA1}"
          requires:
            - build_deploy


workflows:
  version: 2.1
  build:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master